### ISSUE TITLE
path to svn.exe

### ISSUE THREAD

**Issue by jochenjonc** [jondot/nchurn#5]
It would be nice if the path to svn.exe could be set via a commandline argument. In all my projects svn is bundled with the source and no installation is needed on de development machine or on the buildserver. On the development machines TortoiseSVN is installed.

I think it can be usefull for HG, Git en TFS users also.

**Comment by jondot** [comment]
Hi,

Most tools that i'm familiar with assume existence of those, and because of that i took that path in nchurn.

BTW: as an immediate solution, you can always set PATH to your tool before running nchurn.

So I guess one question for me to you would be to elaborate about the reason of bundling svn and not using build server / env facilities, just out of curiosity?

**Comment by jochenjonc** [comment]
There are a few reasons and some are where more decisive then others, so here they are:
- We want our projects to be as independent as possible from the system where they are build on, this means that we bundle everything the buildscript needs. Binaries, but also utilities like NUnit, NCover, ... and also subversion (commandline version).
  The idea is that when a new developer is hired or for some reason a computer has been formatted and reinstalled, the developer just pulls the source-code from the repository runs the buildscript and is ready to develop.
  Only .Net Framework should be installed.
- In the past we have had troubles with changes between Subversion versions and by bundeling SVN with the source the buildscripts always work, even on the buildserver where projects with different subversion clients are build together. Teams weren't happy when their build broke because of a new Subversion version introduced and installed by an other team on the buildserver.
- If SVN is part of the repository it is easier in the buildscript to run the svn.exe command because svn.exe can be found with a relative path, something like ..\Utilities\Subversion\svn.exe.

**Comment by jondot** [comment]
Ok, sound interesting.
During this week I'll think how to incorporate that quickly and post a suggestion here. In the meanwhile can you check if setting the tool in PATH before running nchurn covers it up for you?

**Comment by jochenjonc** [comment]
Svn in PATH works, no problems there.

**Comment by jondot** [comment]
Hi Jochen,
I wanted to hop in and ask if the PATH solution works for you completely?

I'm about to push some features in, it shouldn't be a problem to implement what you asked but i prefer to adhere to KISS in this case.

**Comment by jochenjonc** [comment]
PATH, works but I'm not going to set the PATH on the buildserver.

But don't see this feature as a priority, I'm going to show it to some other guys at the company and if they think every build should have a nchurn, we can always help you out with a patch.

**Comment by jondot** [comment]
Hi Jochen, I was thinking more towards setting PATH in each project's build script just pre-initially, before running nchurn. Since in either case you're adding a command for running nchurn, just above that run PATH=%PATH%;...where SVN is

Does that make sense?

**Comment by jochenjonc** [comment]
This is no really an option, there are always multiple builds running on the buildserver. In the past, we had a project that put an assembly in the GAC during the build and removed it afterwards, but those few minutes where enough to break the build of other projects.

Personally I think that being able to provide the path to the repository client (svn, git, ...) is the best solution.

**Comment by jondot** [comment]
Ok, i was under the influence that once you add PATH variable through build script it'll be isolated from other builds since it would run in its own process. 
I'll check that theory out just out of curiousity.

I'll move forward to implement specifying tool location. It'll be out this week :)

**Comment by jondot** [comment]
Hi Jochen, you can check out the 0.4 build from downloads. it has path implemented.
let me know if it works as you expect

**Comment by jochenjonc** [comment]
Hello Jon,

It works, thanks. When I have some time I will put it in the build-scripts and  have a look at the results.

**Comment by jondot** [comment]
Great!
I've also just pushed an xslt transform for your build in /extras/build
If you're using CI like TeamCity or CC.NET, its easy to set up, using nchurn xml report.
