### ISSUE TITLE
Ability to run analysis against existing log in a file 

### ISSUE THREAD

**Issue by orangy** [jondot/nchurn#6]
Querying SVN for 3years data is quite long. I'd like to get verbose log once and then analyse it in various ways.

**Comment by orangy** [comment]
Actually, this implies subpath filtering and date filtering by NChurn instead of SVN command.

**Comment by orangy** [comment]
Oops, closed by mistake. Please reopen.

**Comment by jondot** [comment]
Great idea.
I'll be sure to implement this week.
In the same regard, i'd like to point out that i'm planning some profiling and optimizations stage (for this kind of data); but i'm not sure it will happen at the same time.

**Comment by jondot** [comment]
implemented.
see
nchurn -i inputfile.log -a svn

feeding nchurn a file with `-i`, and then specifying the suitable adapter with `-a`

hope this helps!.
